{% set version = "0.3.3" %}

package:
  name: svgutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/svgutils/svgutils-{{ version }}.tar.gz
  sha256: ef0825a818a3ea31eed759e246c0057961006905fd1eac99de9b35bbde77bab4

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - lxml

  run:
    - python
    - lxml

test:
  imports:
    - svgutils

about:
  home: https://svgutils.readthedocs.io
  license: MIT
  summary: |
    Python SVG editor that allows to automatically create publication ready
    composite SVG figures.
  description: |
    This is an utility package that helps to edit and concatenate SVG files.
    It is especially directed at scientists preparing final figures for
    submission to journal. So far it supports arbitrary placement and scaling
    of svg figures and adding markers, such as labels.
  doc_url: https://svgutils.readthedocs.io
  dev_url: https://github.com/btel/svg_utils

extra:
  recipe-maintainers:
    - johanneskoester
