{% set version = "0.3.4" %}

package:
  name: svgutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/svgutils/svgutils-{{ version }}.tar.gz
  sha256: 9ef48f44cb1d460a7747dd02694200fda25eb9faf6dea392118def2695e0e053

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >= 3.6
    - pip
    - lxml

  run:
    - python >= 3.6
    - lxml

test:
  imports:
    - svgutils

about:
  home: https://svgutils.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: |
    Python SVG editor that allows to automatically create publication ready
    composite SVG figures.
  description: |
    This is an utility package that helps to edit and concatenate SVG files.
    It is especially directed at scientists preparing final figures for
    submission to journal. So far it supports arbitrary placement and scaling
    of svg figures and adding markers, such as labels.
  doc_url: https://svgutils.readthedocs.io
  dev_url: https://github.com/btel/svg_utils

extra:
  recipe-maintainers:
    - johanneskoester
