travis:
  secure:
    BINSTAR_TOKEN: ZI+vulBOLKpei2CglAUJA/dH2cVlvlDB/yEivYVn2CXzGqN2E0RZ6PCM6IV6XEIcV8kP6QxQHHktrAyIvZlLre1bSsepcI0jmFLgQ3LIGig0w+EP+v+QwkfkD1fkGftoAMTEp53ZeOYOR7gBL/Pdd5BlSx7MTj9+kY5IvBy/1GEeCU6S/ucNF/F4g4Xtj85AURxaKI6sTHLOJ+kAw02pplb2tDfXaIyJXIeYyN+6G4xn1RelSLp8uvAtGSIT3h0RcwfCmpT0hWYtSIYqHlGjMH4f3EYKTEmXm40NttQFMdYup2FRuca4uKV5wWWNGIlDxbXDR0dUsfYXp0fKQ0+jJvWQ4BN5I9ECdxB3NHyN3eklRhhhM80JHDUn/psjks2vCw4UG6dFKSr7cEQhceAK4xHXbmNd6TkEf4eq3kkjLE5WT6WZzQID9M6M7nq+OUzAgXBfLGb6p9xVTsUygfUFDExijDxvnR2YUJbC2/cxRULt/6r3Bv+LIl3spcVM7Y0NGJj0L52Hd+cyZ1caEMGErmqK16M4TfYAGwQCNpxUGmKJ5HGnAfzn0bzfYOol4hiH03Ug+yQ3B6tEepfAgTQ1L8qqqQa5t+QTeAlaf+i/iwp5FNNuPpHhlX+4sdM+2AfWSpoZNXnX0f+6TaGQl4EGWqqENrO15Vc/Cozhf348fhs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
