travis:
  secure:
    BINSTAR_TOKEN: nhDgRXj+kI7uk9cefQTcUApMW9yCWtjeDWXSXZU4iJlFkBkJ+luLwRLAJSQGb5gPp4X3nnZBvJsNUdbyjlhuNy3UXNHhDb3ZHQQZjgudBO0CJraJEm2Ya0Ke2XZYwJ4ZuuzgcaVDj0mBt2Xdsjfhd1WuKDbxjgqBSDlcqfNHnViMUGiBZgsamA/fMevQEnvD720b/oIEEID71IwUH/SCwFnAiclqb4b1sfuhyucYo4svo/nTcguhTguZq733kCmtzcOfbTpLl+s3LI3YoZj/hGvoRgw0NwaAci6uC0V5BakSeptcoU3YV0XmG6+4f/Qop/GPu7lptgBmlDiabcCOpXIXS2TdjcyK7kiRq1XoPPKYvfWoToqdzW0bkN4ikVR5TOzzW1jdUiA/4eog1+MlZsC5JvQugCYeEIKNmS0FhK5qDvjwJwYJKaSjp9IuURDSkryXEC09cuVR3uJVBQRBi9j3TcmbWUTUYLKJdF/LgpJKRM1ijJlWvr++WswbccvpUXcclz8NL156UfqdBBHTXS6f+DOVk6sKNdCm3dQxZ1por943ZdkAplMb+w2uEsUUUoRMxW7w3eYoaL1WVc3RZlLFJTJEaa0bmgmCipTTGsvOmjDseCpVuRHQqT9r3cIMlxQYvDltvKxdw4SH6zMt77D7NzFDtd0Tg0jLgm1X7MM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
